// <auto-generated />
namespace PaymentApp.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class transactionpaid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transactionpaid));
        
        string IMigrationMetadata.Id
        {
            get { return "201704291557183_transactionpaid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
